name: openapi_spec
description: OpenAPI Specification generator using native Dart code, as well as an all-in-one parser of existing specifications.
version: 0.1.0
maintainer: Taza Technology LLC
repository: https://github.com/tazatechnology/openapi_spec
issue_tracker: https://github.com/tazatechnology/openapi_spec/issues
homepage: https://tazatechnology.com
documentation: https://github.com/tazatechnology/openapi_spec

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  yaml: ^3.1.2
  path: ^1.8.3
  
  # For generated client code
  intl: ^0.18.1
  http: ^0.13.6
  recase: ^4.1.0

dev_dependencies:
  build_runner: ^2.3.2
  lints: ^2.0.0
  freezed: ^2.3.3
  json_serializable: ^6.7.0
  test: ^1.24.3