name: 'Test'
on: push

jobs:
  Test:
    name: 'openapi_sec'
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Run tests
        run: |
          export TERM=xterm
          make test